### PR TITLE
🥶 feautre

### PR DESCRIPTION
**Pull request by mohfez**
Fixed 1 bug and added 2 features!!1!

### CODE REVIEW

**Comment by VictorVictini** [comment]
🥶

**Comment by VictorVictini** [comment]
It seems to provide current time data when given a data in the future
Guessing this is cus it gets n candles from that time, don't know if we wanna handle that or not

**Comment by mohfez** [comment]
good point, how should we handle it boss?

**Comment by VictorVictini** [comment]
probably should, I'll leave it to you

**Comment by VictorVictini** [comment]
oh wait I misread, I meant apply an error*

**Comment by VictorVictini** [comment]
LGTM

**Pull request merged**
